@startuml useCaseDiagram
skinparam actorStyle Hollow
skinparam actorBorderColor black
skinparam actorFontColor black
skinparam useCaseBackgroundColor AliceBlue
skinparam useCaseBorderColor RoyalBlue
skinparam useCaseFontColor black
skinparam useCaseFontSize 14

actor GuestUser
actor LoggedUser
actor Journalist
actor Manager
actor Director
left to right direction

rectangle System {
  usecase Create_Article
  usecase Filter_Newspapers_Copy_By_Date
  usecase Filter_Articles_By_Categories
  usecase Approve_Article
  usecase Authenticate
  usecase Register
  usecase Browse_Newspapers
  usecase Filter_Newspapers
  usecase View_Newspaper_Copy
  usecase Search_Articles
  usecase Submit_Article_for_Approval
  usecase Comment_on_Article
  usecase Approve_Newspaper_Copy
  usecase By_title
  usecase By_publisher
  usecase View_Articles
}

Register -[hidden]down-> Search_Articles
Register -[hidden]down-> View_Newspaper_Copy
Browse_Newspapers -[hidden]down-> Authenticate
Filter_Newspapers_Copy_By_Date -[hidden]down-> View_Articles


LoggedUser --|> GuestUser
Journalist --|> LoggedUser
Manager --|> LoggedUser
Director --|> LoggedUser

GuestUser -up-> Authenticate
GuestUser -up-> Register
GuestUser -up-> Browse_Newspapers
GuestUser -up-> Filter_Newspapers
GuestUser -up-> View_Articles
GuestUser -up-> Filter_Articles_By_Categories
GuestUser -up-> View_Newspaper_Copy
GuestUser -up-> Search_Articles
GuestUser -up-> Filter_Newspapers_Copy_By_Date

Journalist -down-> Submit_Article_for_Approval
Journalist -down-> Create_Article

LoggedUser -down-> Comment_on_Article

Manager -down-> Approve_Article

Director -down-> Approve_Newspaper_Copy
Filter_Newspapers <.. By_publisher : <<extends>>
Filter_Newspapers <.. By_title : <<extends>>
@enduml